[package]
name = "revm-provider"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
ethers = "2.0.7"
#tokio = { version = "1.28", features = ["full"] }
serde = "1.0"
serde_json = "1.0"
revm = "3.3.0"
